spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangyaoyi/config-repo.git

server:
  port: 20000

eureka:
  client:
    region: sz
    availability-zones:
      sz: sz-zone1,sz-zone2
    service-url:
      sz-zone1: http://sz-zone1-1:10000/eureka,http://sz-zone1-2:10000/eureka
      sz-zone2: http://sz-zone2-1:10000/eureka
---
spring:
  profiles: sz-zone1-1
eureka:
  instance:
    hostname: sz-zone1-1
    metadata-map:
      zone: sz-zone1
---
spring:
  profiles: sz-zone1-2
eureka:
  instance:
    hostname: sz-zone1-2
    metadata-map:
      zone: sz-zone1
---
spring:
  profiles: sz-zone2-1
eureka:
  instance:
    hostname: sz-zone2-1
    metadata-map:
      zone: sz-zone2